"""Module contains the TNTU Assistant agent."""

from typing import List, Optional, Union
from langchain_core.messages import MessageLikeRepresentation
import dspy
from ml.agent.tools import AVAILABLE_TOOLS
from ml.config.settings import settings
from ml.agent.exceptions import InvalidModelException
from ml.config.logger import get_logger

logger = get_logger(__name__)


class TNTUAssistantSignature(dspy.Signature):
    """
    You are TNTU Assistant, a professional and helpful AI assistant for Ternopil National Technical University named after Ivan Puluj (TNTU).

    Your main responsibilities:
    1. Provide accurate and helpful information about the university, its history, and Ivan Puluj.
    2. Assist students and applicants with questions about faculties, specialties, and admission requirements.
    3. Provide information about the educational process, schedules, and exam sessions.
    4. Answer questions about campus life, dormitories, and student organizations.
    5. Communicate in the same language as the user's message (defaulting to Ukrainian if unclear).
    6. Be polite, attentive, and respectful to all users.

    Important rules:
    - If a question is outside your competence or specific university data is missing, honestly acknowledge it.
    - Do NOT make up facts about university policies or dates.
    - Use the same language as the user's message when responding.
    """  # noqa: D204, D205
    chat_history: List[MessageLikeRepresentation] = dspy.InputField(desc="The full chat history between the user and the agent.")
    user_message: str = dspy.InputField(desc="The latest user message.")
    response: str = dspy.OutputField(desc="The response to the user message.")


class TNTUAssistantAgent(dspy.Module):
    """TNTU assistant agent."""

    def __init__(
        self,
        tools: List[dspy.Tool] = AVAILABLE_TOOLS,
        model_path: Optional[str] = None,
    ) -> None:
        """
        Initialize the TNTU Assistant Agent.

        Parameters
        ----------
        tools : List[dspy.Tool]
            The tools to use for the agent.
        model_path : Optional[str]
            Path to load a pre-trained model from. If provided, loads the model.
        """
        self._core = dspy.ReAct(TNTUAssistantSignature, tools=tools)
        if model_path:
            self.load(model_path)

    def forward(
        self,
        user_message: str,
        chat_history: List[MessageLikeRepresentation] = [],
    ) -> dspy.Prediction:
        """
        Forward the TNTU assistant agent.

        Parameters
        ----------
        user_message : str
            The user message to generate a response for.
        chat_history : List[MessageLikeRepresentation]
            The chat history for context.

        Returns
        -------
        Prediction
            The response generated by the agent.
        """
        return self._core(user_message=user_message, chat_history=chat_history)

    @staticmethod
    def _dict_to_example(item: dict) -> dspy.Example:
        """
        Convert a dictionary into a `dspy.Example` following the agent schema.

        Parameters
        ----------
        item : dict
            Dictionary that must contain the keys `user_message`, `response`,
            and optionally `chat_history`.

        Returns
        -------
        dspy.Example
            Example with inputs set to `user_message` and
            `chat_history` (if provided).
        """
        user_message: str = item["user_message"]
        chat_history: List[MessageLikeRepresentation] = item.get("chat_history", [])
        response: str = item["response"]

        example = dspy.Example(user_message=user_message, chat_history=chat_history, response=response)
        # Inputs according to schema
        return example.with_inputs("user_message", "chat_history")

    @classmethod
    def ensure_examples(
        cls,
        dataset: List[Union[dspy.Example, dict]],
    ) -> List[dspy.Example]:
        """
        Ensure a list of dataset items are `dspy.Example` instances.

        Parameters
        ----------
        dataset : List[Union[dspy.Example, dict]]
            List possibly containing dictionaries shaped like the schema.

        Returns
        -------
        List[dspy.Example]
            Converted list of `dspy.Example` items.
        """
        examples: List[dspy.Example] = []
        for item in dataset:
            if isinstance(item, dspy.Example):
                examples.append(item)
            elif isinstance(item, dict):
                examples.append(cls._dict_to_example(item))
            else:
                raise TypeError(
                    "Dataset must contain dspy.Example or dict items conforming to the schema."
                )
        return examples

    def is_healthy(self) -> bool:
        """
        Check if the agent is healthy and properly configured.

        Returns
        -------
        bool
            True if agent is healthy, False otherwise.
        """
        try:
            # Check if DSPy is configured
            if not hasattr(dspy.settings, 'lm') or dspy.settings.lm is None:
                return False
            return True
        except Exception as e:
            logger.error(f"Health check failed: {e}")
            return False


def _configure_dspy(model_name: Optional[str] = None, temperature: Optional[float] = None) -> None:
    """
    Configure DSPy with the specified language model.

    Parameters
    ----------
    model_name : Optional[str]
        Name of the LLM model to use. If None, uses default from settings.
    temperature : Optional[float]
        Temperature for the model. If None, uses default from settings.

    Raises
    ------
    InvalidModelException
        If the model name is not in the allowed list.
    """
    model = model_name or settings.DEFAULT_LLM
    temp = temperature if temperature is not None else settings.DEFAULT_LLM_TEMPERATURE

    # Validate model name
    if model not in settings.ALLOWED_LLM_MODELS:
        raise InvalidModelException(model_name=model, allowed_models=settings.ALLOWED_LLM_MODELS)

    # Configure DSPy with the LM
    lm = dspy.LM(
        model=f"openai/{model}",
        api_key=settings.OPENAI_API_KEY,
        temperature=temp,
        max_tokens=settings.AGENT_MAX_TOKENS,
        cache=False
    )
    dspy.configure(lm=lm)
    logger.info(f"DSPy configured with model: {model}, temperature: {temp}")


def configure_dspy_for_request(model_name: Optional[str] = None, temperature: Optional[float] = None) -> dspy.context:
    """
    Create a DSPy context for a specific request with optional model/temperature override.

    This should be used as a context manager in async tasks instead of calling dspy.configure().
    If no model_name or temperature is provided, uses the current/default DSPy configuration.

    Parameters
    ----------
    model_name : Optional[str]
        Name of the LLM model to use. If None, uses current/default model.
    temperature : Optional[float]
        Temperature for the model. If None, uses current/default temperature.

    Returns
    -------
    dspy.context
        DSPy context manager that should be used with 'with' statement.

    Raises
    ------
    InvalidModelException
        If the model name is not in the allowed list.

    Examples
    --------
    >>> with configure_dspy_for_request(model_name="gpt-4", temperature=0.7):
    ...     prediction = agent.forward(...)
    """
    # If no overrides provided, use current/default configuration
    if model_name is None and temperature is None:
        # Use the current LM from settings if available
        if hasattr(dspy.settings, 'lm') and dspy.settings.lm is not None:
            return dspy.context(lm=dspy.settings.lm)
        # Otherwise create default LM
        model_name = settings.DEFAULT_LLM
        temperature = settings.DEFAULT_LLM_TEMPERATURE

    model = model_name or settings.DEFAULT_LLM
    temp = temperature if temperature is not None else settings.DEFAULT_LLM_TEMPERATURE

    # Validate model name
    if model not in settings.ALLOWED_LLM_MODELS:
        raise InvalidModelException(model_name=model, allowed_models=settings.ALLOWED_LLM_MODELS)

    # Create LM instance
    lm = dspy.LM(
        model=f"openai/{model}",
        api_key=settings.OPENAI_API_KEY,
        temperature=temp,
        max_tokens=settings.AGENT_MAX_TOKENS,
        cache=False
    )

    # Return context manager for async-safe configuration
    return dspy.context(lm=lm)


# Initialize DSPy with default settings
try:
    _configure_dspy()
except Exception as e:
    logger.error(f"Failed to initialize DSPy: {e}")
    raise

# Create and export the global agent instance
agent = TNTUAssistantAgent()
